# Generated by Django 6.0.2 on 2026-02-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dudu', '0002_alter_booking_package_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='num_people',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
