# Generated by Django 5.2.11 on 2026-02-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dudu', '0002_userprofile_address_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('option', models.CharField(blank=True, max_length=100)),
                ('travel_date', models.DateField()),
                ('no_of_people', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
