# Generated by Django 6.0.2 on 2026-02-13 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dudu', '0003_enquiry_city_enquiry_num_people_enquiry_travel_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package',
            new_name='Industrial',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='package',
            new_name='industrial',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='package',
            new_name='industrial',
        ),
        migrations.AlterModelTable(
            name='industrial',
            table='industrials',
        ),
    ]
