# Generated by Django 5.2.11 on 2026-02-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dudu', '0004_newsevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
