# Generated by Django 5.2.11 on 2026-02-13 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dudu', '0005_chatbotlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishes', to='dudu.user')),
            ],
            options={
                'verbose_name_plural': 'Wishes',
                'db_table': 'wish',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ChatbotLog',
        ),
    ]
