# Generated by Django 5.2.11 on 2026-02-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dudu', '0007_alter_wish_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('icon', models.CharField(default='fa-users', max_length=50)),
            ],
        ),
    ]
